### PR TITLE
Added link to page on addons.mozilla.org.

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by ttaubert** [comment]
Sorry, I must have forgot about this. The readme includes a link now and did for a while... not sure since when. Thanks for your PR, I'm bad a this.

**Comment by ypid** [comment]
Can happen. Thanks for the plugin :+1:.

**Comment by ypid** [comment]
@ttaubert State that the project is DISCONTINUED. Can you maybe recommend a successor?

**Comment by ttaubert** [comment]
Please don't comment on unrelated pull requests. I can't recommend a successor but the source code is still available.

**Pull request closed without merging**
